### PR TITLE
Phineas pls accept it’s kitty kitty

### PR DESCRIPTION
**Pull request by loom4k**

### CODE REVIEW

**Comment by alii** [comment]
This is not a real language

**Comment by cnrad** [comment]
Dear Loom4k,

We regret to inform you that your pull request to the branch **cat/nya** will not be merged. We've found that "In cool Language" is not a suitable language for us to add at the moment, we apologize for the inconvenience.

Thanks,
github.com/cats Team

**Comment by Loom4k** [comment]
stfu lmaoo. kitty kitty is universal translation :/

**Comment by loom4k** [comment]
but it’s fine ill find better kitty kitty

**Comment by imfunniee** [comment]
sad momento

**Pull request closed without merging**
